---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0

      - name: "Set up JDK 11"
        uses: "actions/setup-java@v2"
        with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven

      - name: "Build .jar"
        run: mvn clean package spring-boot:repackage -e
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            target/scenario-quality-checker-io-0.1.jar

      - name: "Javadocs"
        run: mvn javadoc:javadoc
      - uses: actions/upload-artifact@v2
        with:
          name: Javadoc
          path: target/javadoc-bundle-options/javadoc-options-javadoc-resources.xml
